packages:
  - name: api
    functions:
      - name: v1
        runtime: 'python:3.11'
        limits:
          timeout: 30000
        actions:
          - name: index
            runtime: 'python:3.11'
          - name: hello