packages:
  - name: v1
    environment:
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_PASS: ${ADMIN_PASS}
      JWTKey: ${JWTKey}
      JWTSECRET: ${JWTSECRET}
      LOG_DESTINATIONS: ${LOG_DESTINATIONS}
    functions:
      - name: index
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: login
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: logout
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: create
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: read
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: update
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: delete
        runtime: 'python:3.11'
        limits:
          timeout: 30000
  - name: frontend
    environment:
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_PASS: ${ADMIN_PASS}
      JWTKey: ${JWTKey}
      JWTSECRET: ${JWTSECRET}
      LOG_DESTINATIONS: ${LOG_DESTINATIONS}
    functions:
      - name: home
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: create
        runtime: 'python:3.11'
        limits:
          timeout: 30000