packages:
  - name: api
    functions:
      - name: index
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: hello
        runtime: 'python:3.11'
        limits:
          timeout: 30000