environment:
  ADMIN_NAME: ${ADMIN_NAME}
  ADMIN_PASS: ${ADMIN_PASS}
  JWTSECRET: ${JWTSECRET}
  LOG_DESTINATIONS: '[{"logtail":{"token":"${LOGTAIL}"}}]'
packages:
  - name: auth
    functions:
      - name: login
        runtime: 'python:3.11'
        limits:
          timeout: 30000
      - name: logout
        runtime: 'python:3.11'
        limits:
          timeout: 30000
  - name: user
    functions:
      - name: home
        runtime: 'python:3.11'
        limits:
          timeout: 30000
  - name: example
    functions:
      - name: home
        environment:
          AUTHREQUIRED: 'false'
          HTTPMETHODS: 'get,post'
        runtime: 'python:3.11'
        limits:
          timeout: 30000